#конфиг для автотестов 
[pytest]
DJANGO_SETTINGS_MODULE = app.settings#подруб настроек
python_files = tests.py test_*.py *_tests.py#чо вообще надо запускать звездоски нужны для того чтобы если чото дописано например test_ghfvgh.py он считался тестовым файлом