#главный конфиг проекта при старте импортирует его целиком 

"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path#для работы с путями 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent# путь к текущему файлу

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p2#iwg4a362hz@*kt91rip_k3+p=(!6u#fc^k%n$2axzrnf&+q'#секретный ключ для криптографии сессии токены куки сброс пародей 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True# режим отладки показывает ошибки в проде обязательно фалзе иначе данные о серваке утекут

ALLOWED_HOSTS = []# список доменов с которых разрешено обслуж сайт. разрешает локалхост в проде пишут реальный домен 


# Application definition
#список всех подкл приложений 
INSTALLED_APPS = [
    'django.contrib.admin',#админка
    'django.contrib.auth',#авторизация
    'django.contrib.contenttypes',#система типов контента
    'django.contrib.sessions',#сервисные сессии 
    'django.contrib.messages',#сообщения 
    'django.contrib.staticfiles',#статистика 
    'corsheaders',#запросы с разных доменов
    'rest_framework',#движок апишки
    'store',#приложение 
]
#прослойки через которые проходит каждый запрос по пути к вьюхе и каждый ответ на обратном пути
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',#добавляет cors заголовки
    'django.middleware.security.SecurityMiddleware',#заголовки безопастности https
    'django.contrib.sessions.middleware.SessionMiddleware',#подключает сессии
    'django.middleware.common.CommonMiddleware',#служебное 
    'django.middleware.csrf.CsrfViewMiddleware',#защита от csrf атак(проверка токена в формах)
    'django.contrib.auth.middleware.AuthenticationMiddleware',#добавляет текущ полз
    'django.contrib.messages.middleware.MessageMiddleware',#сообщения 
    'django.middleware.clickjacking.XFrameOptionsMiddleware',#защита от clickjacking
]
#указывает какой модуль содержит корневую маршрутизацию URL крч разбор адресов
ROOT_URLCONF = 'app.urls'
#html шаблоны
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',#какой движок шаблонов
        'DIRS': [#где искать папки с шаблонами 
            BASE_DIR / "templates"
        ],
        'APP_DIRS': True,#ищет шаблоны внутри каждого приложения
        'OPTIONS': {
            'context_processors': [#
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'#


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#настройка бдшки 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
#валидаторы пароля при реге смене пароля
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',#пароль не должен быть похож на имя или маил пользователя
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',#минимальная длина пароля 8
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',#запрет частых паролей
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',#пароль не может быть только из цифр
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'#язык по умолчанию

TIME_ZONE = 'UTC'#часовой пояс

USE_I18N = True#переводы

USE_TZ = True#хранение дат в бд с уч таймзон


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'#префикс по которому статистика раздаётся

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#белый список по которым браузер разрешает делать запросы api
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
]

CSRF_TRUSTED_ORIGINS = ["http://localhost:5173"]

MEDIA_ROOT = BASE_DIR / "media"#папка на диске куда сохр загруж пользователем файлы
MEDIA_URL = "/media/"